pages:
  cache:
    paths:
      - node_modules/
  script:
    - nvm use v12.20.1
    - rm -rf public/*
    - rm -rf docs/.vuepress/dist
    - yarn install
    - yarn build --dest public
  artifacts:
    paths:
      - public
  only:
    - master
